<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Vérification du vote soumis</h3>
    </div>
    <div class="modal-body">
        <table class="table table-hover">
            <tbody>
    <?php 
        require_once '../classes/db.class.php';

        $mysql = new DB();
        $datas = $_GET['data'];
        foreach ($datas as $etu_id => $v) {
            $etu = $mysql->getEtu($etu_id);
    ?>
            <tr>
                <td><?php echo $etu['nom']; ?></td>
                <td><?php echo $etu['prenom']; ?></td>
                <td><?php echo (isset($v['no_vote']) && $v['no_vote'] == "on") ? "Pas de note": $v['note']; ?></td>
            </tr>
    <?php
        }
    ?>
            </tbody>
        </table>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <button class="btn btn-primary">Save changes</button>
    </div>
</div>
