<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i></button>
    <h3 id="myModalLabel">Formulaire non valide</h3>
  </div>
  <div class="modal-body">
    <p>Le formulaire n'est pas bien complété. Des champs requis ont peut être été omis. Vous pouvez vérifier également que les champs saisis sont valides (symbol ok vert).</p>
    <p>Ou bien vous avez déjà soumis ce formulaire. Rechargez la page pour en soumettre un nouveau. Merci.</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Fermer</button>
  </div>
</div>
