######################################################################
# Automatically generated by qmake (3.0) jeu. avr. 10 10:36:05 2014
######################################################################

TEMPLATE = app
TARGET = LO21D6
INCLUDEPATH += .

QT += widgets
QT += xml

# Input
HEADERS += UTProfiler.h
SOURCES += main.cpp UTProfiler.cpp
